version: '3'
services:
  python3:
    user: "1000:1000"
    restart: always
    build: .
    container_name: 'pytorch'
    working_dir: '/pytorchStudy/'
    tty: true
    volumes:
      - ./:/pytorchStudy/
